### ISSUE TITLE
[Sugestion/ask] Teleporter scrollbar

### ISSUE THREAD

**Issue by Manka-Muakido** [akarnokd/ThePlanetCrafterMods#3]
first of all: sorry, i did try find a contact of mail on you profile but i cant see one so i will create a issue here.

can you make a mod to put a scroll in the teleport list? the last update added the teleport but the list of points did not have a scroll so if you has too much teleport point this happens:

https://i.imgur.com/pp73QSl.png
![image](https://user-images.githubusercontent.com/39040633/169566666-3e342295-80b9-4919-945b-ca51d477a1cd.png)

and also/or a mod that control the UI size in general you can put a hotkey to get all the UI elements smaller or bigger is a temp solution i guess control of the canvas UI should be easy to do???

anyway thanks and sorry again for the wrong place to communicate

**Comment by akarnokd** [comment]
This issue list is mainly for bugs/enhancements for existing mods of mine. Please post mod requests on the Discord/modding channel.

Your report is more of a bug so please report it on the bugs channel.

As for the feature, I doubt this can be fixed by mods because the screen structure has to be modified in the Unity editor by the game devs.

**Comment by akarnokd** [comment]
Hi. After looking into the game, I found a relatively simple way of doing this. You can check out my new mod:

https://github.com/akarnokd/ThePlanetCrafterMods/releases/tag/v65 -> akarnokd-UITeleporterScroll.zip
